# Copyright (c) NukeLab Development Team.
# Distributed under the terms of the BSD-2-Clause license.

# OpenFOAM CFD environment.
ARG REGISTRY=ghcr.io/nukehub-dev
ARG BASE_TAG=v1.0.0
ARG BASE_IMAGE=${REGISTRY}/conda-base:${BASE_TAG}

FROM $BASE_IMAGE

ARG OPENFOAM_VERSION="v2312"

# TODO: install OpenFOAM and common CFD utilities
