# Copyright (c) NukeLab Development Team.
# Distributed under the terms of the BSD-2-Clause license.

# Cardinal: MOOSE + OpenMC coupling environment.
ARG BASE_TAG=v1.0.0
ARG BASE_IMAGE=ghcr.io/nukelab/moose:${BASE_TAG}

FROM $BASE_IMAGE

ARG CARDINAL_BRANCH="master"

# TODO: build Cardinal against the pre-installed MOOSE and OpenMC
