# Copyright (c) NukeLab Development Team.
# Distributed under the terms of the BSD-2-Clause license.

# MOOSE multiphysics framework environment.
ARG REGISTRY=ghcr.io/nukehub-dev
ARG BASE_TAG=v1.0.0
ARG BASE_IMAGE=${REGISTRY}/nuclear-base:${BASE_TAG}

FROM $BASE_IMAGE

ARG MOOSE_BRANCH="master"

# TODO: install PETSc, libMesh (if not sufficient from nuclear-base), and MOOSE
