# Copyright (c) NukeLab Development Team.
# Distributed under the terms of the BSD-2-Clause license.

# MOOSE multiphysics framework environment.
ARG BASE_TAG=v1.0.0
ARG BASE_IMAGE=ghcr.io/nukelab/nuclear-base:${BASE_TAG}

FROM $BASE_IMAGE

ARG MOOSE_BRANCH="master"

# TODO: install PETSc, libMesh (if not sufficient from nuclear-base), and MOOSE
